<?php

declare(strict_types=1);

/*
 * TestForDatetimeInModelLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TestForDatetimeInModelLib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysAndValuesBodyMatcher;
use Core\TestCase\TestParam;
use TestForDatetimeInModelLib\Controllers\FormParamsController;
use TestForDatetimeInModelLib\Exceptions;
use TestForDatetimeInModelLib\Models;
use TestForDatetimeInModelLib\Utils\DateTimeHelper;

class FormParamsControllerTest extends BaseTestController
{
    /**
     * @var FormParamsController FormParamsController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getFormParamsController();
    }

    public function testSendDateArray()
    {
        // Parameters for the API call
        $dates = TestParam::custom('["1994-02-13","1994-02-13"]', [DateTimeHelper::class, 'fromSimpleDateArray']);

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createSendDateArray($dates);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->bodyMatcher(KeysAndValuesBodyMatcher::init(TestParam::object('{"passed":true}')))
            ->assert();
    }

    public function testSendRfc3339DateTimeArray()
    {
        // Parameters for the API call
        $datetimes = TestParam::custom(
            '["1994-02-13T14:01:54.9571247Z","1994-02-13T14:01:54.9571247Z"]',
            [DateTimeHelper::class, 'fromRfc3339DateTimeArray']
        );

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createSendRfc3339DateTimeArray($datetimes);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->bodyMatcher(KeysAndValuesBodyMatcher::init(TestParam::object('{"passed":true}')))
            ->assert();
    }

    public function testSendRfc1123DateTimeArray()
    {
        // Parameters for the API call
        $datetimes = TestParam::custom(
            '["Sun, 06 Nov 1994 08:49:37 GMT","Sun, 06 Nov 1994 08:49:37 GMT"]',
            [DateTimeHelper::class, 'fromRfc1123DateTimeArray']
        );

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createSendRfc1123DateTimeArray($datetimes);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->bodyMatcher(KeysAndValuesBodyMatcher::init(TestParam::object('{"passed":true}')))
            ->assert();
    }

    public function testSendUnixDateTimeArray()
    {
        // Parameters for the API call
        $datetimes = TestParam::custom(
            '[1484719381,1484719381]',
            [DateTimeHelper::class, 'fromUnixTimestampArray']
        );

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createSendUnixDateTimeArray($datetimes);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->bodyMatcher(KeysAndValuesBodyMatcher::init(TestParam::object('{"passed":true}')))
            ->assert();
    }

    public function testSendRfc1123DateTime()
    {
        // Parameters for the API call
        $datetime = TestParam::custom(
            'Sun, 06 Nov 1994 08:49:37 GMT',
            [DateTimeHelper::class, 'fromRfc1123DateTime']
        );

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createSendRfc1123DateTime($datetime);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->bodyMatcher(KeysAndValuesBodyMatcher::init(TestParam::object('{"passed":true}')))
            ->assert();
    }

    public function testSendRfc3339DateTime()
    {
        // Parameters for the API call
        $datetime = TestParam::custom(
            '1994-02-13T14:01:54.9571247Z',
            [DateTimeHelper::class, 'fromRfc3339DateTime']
        );

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createSendRfc3339DateTime($datetime);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->bodyMatcher(KeysAndValuesBodyMatcher::init(TestParam::object('{"passed":true}')))
            ->assert();
    }

    public function testSendUnixDateTime()
    {
        // Parameters for the API call
        $datetime = TestParam::custom('"1484719381"', [DateTimeHelper::class, 'fromUnixTimestamp']);

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createSendUnixDateTime($datetime);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->bodyMatcher(KeysAndValuesBodyMatcher::init(TestParam::object('{"passed":true}')))
            ->assert();
    }

    public function testRfc1123DateTimeInFormAsModel()
    {
        // Parameters for the API call
        $body = TestParam::object('{"dateTime":"Sun, 06 Nov 1994 08:49:37 GMT"}', Models\Rfc1123DateTime::class);

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createSendRfc1123DateTimeInFormAsModel($body);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->assert();
    }

    public function testRfc3339DateTimeInFormAsModel()
    {
        // Parameters for the API call
        $body = TestParam::object('{"dateTime":"1994-02-13T14:01:54.9571247Z"}', Models\DateTimeModel::class);

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createSendRfc3339DateTimeInFormAsModel($body);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->assert();
    }

    public function testUnixDateTimeInFormAsModel()
    {
        // Parameters for the API call
        $body = TestParam::object('{"dateTime":1484719381}', Models\UnixDateTime::class);

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createSendUnixDateTimeInFormAsModel($body);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->assert();
    }

    public function testRfc3339DateTimeArrayInFormAsModel()
    {
        // Parameters for the API call
        $body = TestParam::object(
            '{"dateTime":["1994-02-13T14:01:54.9571247Z","1994-02-13T14:01:54.9571247Z"]}',
            Models\Rfc3339DateTimeArray::class
        );

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createSendRfc3339DateTimeArrayInFormAsModel($body);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->assert();
    }

    public function testRfc1123DateTimeArrayInFormAsModel()
    {
        // Parameters for the API call
        $body = TestParam::object(
            '{"dateTime":["Sun, 06 Nov 1994 08:49:37 GMT","Sun, 06 Nov 1994 08:49:37 GMT"]}',
            Models\Rfc1123DateTimeArray::class
        );

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createSendRfc1123DateTimeArrayInFormAsModel($body);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->assert();
    }

    public function testUnixDateTimeArrayInFormAsModel()
    {
        // Parameters for the API call
        $body = TestParam::object('{"dateTime":[1484719381,1484719381]}', Models\UnixDateTimeArray::class);

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createSendUnixDateTimeArrayInFormAsModel($body);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->assert();
    }

    public function testUnixDateTimeMapInFormAsModel()
    {
        // Parameters for the API call
        $body = TestParam::object('{"dateTime":{"key":1484719381}}', Models\UnixDateTimeMap::class);

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createSendUnixDateTimeMapInFormAsModel($body);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->assert();
    }

    public function testRfc3339DateTimeMapInFormAsModel()
    {
        // Parameters for the API call
        $body = TestParam::object(
            '{"dateTime":{"key":"1994-02-13T14:01:54.9571247Z"}}',
            Models\Rfc3339DateTimeMap::class
        );

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createSendRfc3339DateTimeMapInFormAsModel($body);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->assert();
    }

    public function testRfc1123DateTimeMapInFormAsModel()
    {
        // Parameters for the API call
        $body = TestParam::object(
            '{"dateTime":{"key":"Sun, 06 Nov 1994 08:49:37 GMT"}}',
            Models\Rfc1123DateTimeMap::class
        );

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->createSendRfc1123DateTimeMapInFormAsModel($body);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->assert();
    }
}
