<?php

declare(strict_types=1);

/*
 * TestForDatetimeInModelLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TestForDatetimeInModelLib\Tests;

use Core\Types\CallbackCatcher;

class ClientFactory
{
    public static function create(
        CallbackCatcher $httpCallback
    ): \TestForDatetimeInModelLib\TestForDatetimeInModelClient {
        $clientBuilder = \TestForDatetimeInModelLib\TestForDatetimeInModelClientBuilder::init();
        $clientBuilder = self::addConfigurationFromEnvironment($clientBuilder);
        $clientBuilder = self::addTestConfiguration($clientBuilder);
        return $clientBuilder->httpCallback($httpCallback)->build();
    }

    public static function addTestConfiguration(
        \TestForDatetimeInModelLib\TestForDatetimeInModelClientBuilder $builder
    ): \TestForDatetimeInModelLib\TestForDatetimeInModelClientBuilder {
        return $builder;
    }

    public static function addConfigurationFromEnvironment(
        \TestForDatetimeInModelLib\TestForDatetimeInModelClientBuilder $builder
    ): \TestForDatetimeInModelLib\TestForDatetimeInModelClientBuilder {
        $timeout = getenv('TEST_FOR_DATETIME_IN_MODEL_LIB_TIMEOUT');
        $numberOfRetries = getenv('TEST_FOR_DATETIME_IN_MODEL_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('TEST_FOR_DATETIME_IN_MODEL_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('TEST_FOR_DATETIME_IN_MODEL_LIB_ENVIRONMENT');
        $port = getenv('TEST_FOR_DATETIME_IN_MODEL_LIB_PORT');
        $suites = getenv('TEST_FOR_DATETIME_IN_MODEL_LIB_SUITES');

        if ($timeout !== false && \is_numeric($timeout)) {
            $builder->timeout(intval($timeout));
        }

        if ($numberOfRetries !== false && \is_numeric($numberOfRetries)) {
            $builder->numberOfRetries(intval($numberOfRetries));
        }

        if ($maximumRetryWaitTime !== false && \is_numeric($maximumRetryWaitTime)) {
            $builder->maximumRetryWaitTime(intval($maximumRetryWaitTime));
        }

        if ($environment !== false) {
            $builder->environment($environment);
        }

        if ($port !== false) {
            $builder->port($port);
        }

        if ($suites !== false && \is_numeric($suites)) {
            $builder->suites(intval($suites));
        }

        return $builder;
    }
}
