# test_for_datetime_in_model
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module TestForDatetimeInModel
  # FormParamsController
  class FormParamsController < BaseController
    # TODO: type endpoint description here
    # @param [List of Date] dates Required parameter: Example:
    # @return [ServerResponse] response from the API call
    def create_send_date_array(dates)
      new_api_call_builder
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/form/date',
                                     Server::DEFAULT)
                   .query_param(new_parameter(true, key: 'array'))
                   .form_param(new_parameter(dates, key: 'dates'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept')))
        .response(new_response_handler
                   .deserializer(APIHelper.method(:custom_type_deserializer))
                   .deserialize_into(ServerResponse.method(:from_hash)))
        .execute
    end

    # TODO: type endpoint description here
    # @param [List of DateTime] datetimes Required parameter: Example:
    # @return [ServerResponse] response from the API call
    def create_send_rfc3339_date_time_array(datetimes)
      new_api_call_builder
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/form/rfc3339datetime',
                                     Server::DEFAULT)
                   .query_param(new_parameter(true, key: 'array'))
                   .form_param(new_parameter(datetimes, key: 'datetimes'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept')))
        .response(new_response_handler
                   .deserializer(APIHelper.method(:custom_type_deserializer))
                   .deserialize_into(ServerResponse.method(:from_hash)))
        .execute
    end

    # TODO: type endpoint description here
    # @param [List of DateTime] datetimes Required parameter: Example:
    # @return [ServerResponse] response from the API call
    def create_send_rfc1123_date_time_array(datetimes)
      new_api_call_builder
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/form/rfc1123datetime',
                                     Server::DEFAULT)
                   .query_param(new_parameter(true, key: 'array'))
                   .form_param(new_parameter(datetimes, key: 'datetimes')
                                .value_convertor(proc do |param|
                                  param.map(&:httpdate) unless param.nil?
                                end))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept')))
        .response(new_response_handler
                   .deserializer(APIHelper.method(:custom_type_deserializer))
                   .deserialize_into(ServerResponse.method(:from_hash)))
        .execute
    end

    # TODO: type endpoint description here
    # @param [List of DateTime] datetimes Required parameter: Example:
    # @return [ServerResponse] response from the API call
    def create_send_unix_date_time_array(datetimes)
      new_api_call_builder
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/form/unixdatetime',
                                     Server::DEFAULT)
                   .query_param(new_parameter(true, key: 'array'))
                   .form_param(new_parameter(datetimes, key: 'datetimes')
                                .value_convertor(proc do |param|
                                  param.map { |element| element.to_time.utc.to_i } unless param.nil?
                                end))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept')))
        .response(new_response_handler
                   .deserializer(APIHelper.method(:custom_type_deserializer))
                   .deserialize_into(ServerResponse.method(:from_hash)))
        .execute
    end

    # TODO: type endpoint description here
    # @param [DateTime] datetime Required parameter: Example:
    # @return [ServerResponse] response from the API call
    def create_send_rfc1123_date_time(datetime)
      new_api_call_builder
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/form/rfc1123datetime',
                                     Server::DEFAULT)
                   .form_param(new_parameter(datetime, key: 'datetime')
                                .value_convertor(proc do |param|
                                  param.httpdate unless param.nil?
                                end))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept')))
        .response(new_response_handler
                   .deserializer(APIHelper.method(:custom_type_deserializer))
                   .deserialize_into(ServerResponse.method(:from_hash)))
        .execute
    end

    # TODO: type endpoint description here
    # @param [DateTime] datetime Required parameter: Example:
    # @return [ServerResponse] response from the API call
    def create_send_rfc3339_date_time(datetime)
      new_api_call_builder
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/form/rfc3339datetime',
                                     Server::DEFAULT)
                   .form_param(new_parameter(datetime, key: 'datetime'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept')))
        .response(new_response_handler
                   .deserializer(APIHelper.method(:custom_type_deserializer))
                   .deserialize_into(ServerResponse.method(:from_hash)))
        .execute
    end

    # TODO: type endpoint description here
    # @param [DateTime] datetime Required parameter: Example:
    # @return [ServerResponse] response from the API call
    def create_send_unix_date_time(datetime)
      new_api_call_builder
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/form/unixdatetime',
                                     Server::DEFAULT)
                   .form_param(new_parameter(datetime, key: 'datetime')
                                .value_convertor(proc do |param|
                                  param.to_time.utc.to_i unless param.nil?
                                end))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept')))
        .response(new_response_handler
                   .deserializer(APIHelper.method(:custom_type_deserializer))
                   .deserialize_into(ServerResponse.method(:from_hash)))
        .execute
    end

    # TODO: type endpoint description here
    # @param [Rfc1123DateTime] body Required parameter: Example:
    # @return [ServerResponse] response from the API call
    def create_send_rfc1123_date_time_in_form_as_model(body)
      new_api_call_builder
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/form/rfc1123DateTimeInModel',
                                     Server::DEFAULT)
                   .form_param(new_parameter(body, key: 'body'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept')))
        .response(new_response_handler
                   .deserializer(APIHelper.method(:custom_type_deserializer))
                   .deserialize_into(ServerResponse.method(:from_hash)))
        .execute
    end

    # TODO: type endpoint description here
    # @param [DateTimeModel] body Required parameter: Example:
    # @return [ServerResponse] response from the API call
    def create_send_rfc3339_date_time_in_form_as_model(body)
      new_api_call_builder
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/form/dateTimeInModel',
                                     Server::DEFAULT)
                   .form_param(new_parameter(body, key: 'body'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept')))
        .response(new_response_handler
                   .deserializer(APIHelper.method(:custom_type_deserializer))
                   .deserialize_into(ServerResponse.method(:from_hash)))
        .execute
    end

    # TODO: type endpoint description here
    # @param [UnixDateTime] body Required parameter: Example:
    # @return [ServerResponse] response from the API call
    def create_send_unix_date_time_in_form_as_model(body)
      new_api_call_builder
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/form/unixDateTimeInModel',
                                     Server::DEFAULT)
                   .form_param(new_parameter(body, key: 'body'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept')))
        .response(new_response_handler
                   .deserializer(APIHelper.method(:custom_type_deserializer))
                   .deserialize_into(ServerResponse.method(:from_hash)))
        .execute
    end

    # TODO: type endpoint description here
    # @param [Rfc3339DateTimeArray] body Required parameter: Example:
    # @return [ServerResponse] response from the API call
    def create_send_rfc3339_date_time_array_in_form_as_model(body)
      new_api_call_builder
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/form/rfc3339DateTimeArrayAsModel',
                                     Server::DEFAULT)
                   .form_param(new_parameter(body, key: 'body'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept')))
        .response(new_response_handler
                   .deserializer(APIHelper.method(:custom_type_deserializer))
                   .deserialize_into(ServerResponse.method(:from_hash)))
        .execute
    end

    # TODO: type endpoint description here
    # @param [Rfc1123DateTimeArray] body Required parameter: Example:
    # @return [ServerResponse] response from the API call
    def create_send_rfc1123_date_time_array_in_form_as_model(body)
      new_api_call_builder
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/form/rfc1123DateTimeArrayAsModel',
                                     Server::DEFAULT)
                   .form_param(new_parameter(body, key: 'body'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept')))
        .response(new_response_handler
                   .deserializer(APIHelper.method(:custom_type_deserializer))
                   .deserialize_into(ServerResponse.method(:from_hash)))
        .execute
    end

    # TODO: type endpoint description here
    # @param [UnixDateTimeArray] body Required parameter: Example:
    # @return [ServerResponse] response from the API call
    def create_send_unix_date_time_array_in_form_as_model(body)
      new_api_call_builder
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/form/unixDateTimeArrayAsModel',
                                     Server::DEFAULT)
                   .form_param(new_parameter(body, key: 'body'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept')))
        .response(new_response_handler
                   .deserializer(APIHelper.method(:custom_type_deserializer))
                   .deserialize_into(ServerResponse.method(:from_hash)))
        .execute
    end

    # TODO: type endpoint description here
    # @param [UnixDateTimeMap] body Required parameter: Example:
    # @return [ServerResponse] response from the API call
    def create_send_unix_date_time_map_in_form_as_model(body)
      new_api_call_builder
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/form/unixDateTimeMapAsModel',
                                     Server::DEFAULT)
                   .form_param(new_parameter(body, key: 'body'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept')))
        .response(new_response_handler
                   .deserializer(APIHelper.method(:custom_type_deserializer))
                   .deserialize_into(ServerResponse.method(:from_hash)))
        .execute
    end

    # TODO: type endpoint description here
    # @param [Rfc3339DateTimeMap] body Required parameter: Example:
    # @return [ServerResponse] response from the API call
    def create_send_rfc3339_date_time_map_in_form_as_model(body)
      new_api_call_builder
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/form/rfc3339DateTimeMapAsModel',
                                     Server::DEFAULT)
                   .form_param(new_parameter(body, key: 'body'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept')))
        .response(new_response_handler
                   .deserializer(APIHelper.method(:custom_type_deserializer))
                   .deserialize_into(ServerResponse.method(:from_hash)))
        .execute
    end

    # TODO: type endpoint description here
    # @param [Rfc1123DateTimeMap] body Required parameter: Example:
    # @return [ServerResponse] response from the API call
    def create_send_rfc1123_date_time_map_in_form_as_model(body)
      new_api_call_builder
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/form/rfc1123DateTimeMapAsModel',
                                     Server::DEFAULT)
                   .form_param(new_parameter(body, key: 'body'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept')))
        .response(new_response_handler
                   .deserializer(APIHelper.method(:custom_type_deserializer))
                   .deserialize_into(ServerResponse.method(:from_hash)))
        .execute
    end
  end
end
