<?php

declare(strict_types=1);

/*
 * TestForDatetimeInModelLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TestForDatetimeInModelLib\Models\Builders;

use Core\Utils\CoreHelper;
use TestForDatetimeInModelLib\Models\DateTimeModel;

/**
 * Builder for model DateTimeModel
 *
 * @see DateTimeModel
 */
class DateTimeModelBuilder
{
    /**
     * @var DateTimeModel
     */
    private $instance;

    private function __construct(DateTimeModel $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new date time model Builder object.
     */
    public static function init(\DateTime $dateTime): self
    {
        return new self(new DateTimeModel($dateTime));
    }

    /**
     * Initializes a new date time model object.
     */
    public function build(): DateTimeModel
    {
        return CoreHelper::clone($this->instance);
    }
}
