<?php

declare(strict_types=1);

/*
 * TestForDatetimeInModelLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TestForDatetimeInModelLib\Models\Builders;

use Core\Utils\CoreHelper;
use TestForDatetimeInModelLib\Models\Rfc1123DateTimeArray;

/**
 * Builder for model Rfc1123DateTimeArray
 *
 * @see Rfc1123DateTimeArray
 */
class Rfc1123DateTimeArrayBuilder
{
    /**
     * @var Rfc1123DateTimeArray
     */
    private $instance;

    private function __construct(Rfc1123DateTimeArray $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new rfc 1123 date time array Builder object.
     */
    public static function init(array $dateTime): self
    {
        return new self(new Rfc1123DateTimeArray($dateTime));
    }

    /**
     * Initializes a new rfc 1123 date time array object.
     */
    public function build(): Rfc1123DateTimeArray
    {
        return CoreHelper::clone($this->instance);
    }
}
