<?php

declare(strict_types=1);

/*
 * TestForDatetimeInModelLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TestForDatetimeInModelLib\Models\Builders;

use Core\Utils\CoreHelper;
use TestForDatetimeInModelLib\Models\Rfc1123DateTimeMap;

/**
 * Builder for model Rfc1123DateTimeMap
 *
 * @see Rfc1123DateTimeMap
 */
class Rfc1123DateTimeMapBuilder
{
    /**
     * @var Rfc1123DateTimeMap
     */
    private $instance;

    private function __construct(Rfc1123DateTimeMap $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new rfc 1123 date time map Builder object.
     */
    public static function init(array $dateTime): self
    {
        return new self(new Rfc1123DateTimeMap($dateTime));
    }

    /**
     * Initializes a new rfc 1123 date time map object.
     */
    public function build(): Rfc1123DateTimeMap
    {
        return CoreHelper::clone($this->instance);
    }
}
