<?php

declare(strict_types=1);

/*
 * TestForDatetimeInModelLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TestForDatetimeInModelLib\Models\Builders;

use Core\Utils\CoreHelper;
use TestForDatetimeInModelLib\Models\Rfc1123DateTime;

/**
 * Builder for model Rfc1123DateTime
 *
 * @see Rfc1123DateTime
 */
class Rfc1123DateTimeBuilder
{
    /**
     * @var Rfc1123DateTime
     */
    private $instance;

    private function __construct(Rfc1123DateTime $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new rfc 1123 date time Builder object.
     */
    public static function init(\DateTime $dateTime): self
    {
        return new self(new Rfc1123DateTime($dateTime));
    }

    /**
     * Initializes a new rfc 1123 date time object.
     */
    public function build(): Rfc1123DateTime
    {
        return CoreHelper::clone($this->instance);
    }
}
