<?php

declare(strict_types=1);

/*
 * TestForDatetimeInModelLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TestForDatetimeInModelLib\Models\Builders;

use Core\Utils\CoreHelper;
use TestForDatetimeInModelLib\Models\Rfc3339DateTimeMap;

/**
 * Builder for model Rfc3339DateTimeMap
 *
 * @see Rfc3339DateTimeMap
 */
class Rfc3339DateTimeMapBuilder
{
    /**
     * @var Rfc3339DateTimeMap
     */
    private $instance;

    private function __construct(Rfc3339DateTimeMap $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new rfc 3339 date time map Builder object.
     */
    public static function init(array $dateTime): self
    {
        return new self(new Rfc3339DateTimeMap($dateTime));
    }

    /**
     * Initializes a new rfc 3339 date time map object.
     */
    public function build(): Rfc3339DateTimeMap
    {
        return CoreHelper::clone($this->instance);
    }
}
