<?php

declare(strict_types=1);

/*
 * TestForDatetimeInModelLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TestForDatetimeInModelLib\Models\Builders;

use Core\Utils\CoreHelper;
use TestForDatetimeInModelLib\Models\Rfc3339DateTimeArray;

/**
 * Builder for model Rfc3339DateTimeArray
 *
 * @see Rfc3339DateTimeArray
 */
class Rfc3339DateTimeArrayBuilder
{
    /**
     * @var Rfc3339DateTimeArray
     */
    private $instance;

    private function __construct(Rfc3339DateTimeArray $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new rfc 3339 date time array Builder object.
     */
    public static function init(array $dateTime): self
    {
        return new self(new Rfc3339DateTimeArray($dateTime));
    }

    /**
     * Initializes a new rfc 3339 date time array object.
     */
    public function build(): Rfc3339DateTimeArray
    {
        return CoreHelper::clone($this->instance);
    }
}
