<?php

declare(strict_types=1);

/*
 * TestForDatetimeInModelLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TestForDatetimeInModelLib\Models\Builders;

use Core\Utils\CoreHelper;
use TestForDatetimeInModelLib\Models\ServerResponse;

/**
 * Builder for model ServerResponse
 *
 * @see ServerResponse
 */
class ServerResponseBuilder
{
    /**
     * @var ServerResponse
     */
    private $instance;

    private function __construct(ServerResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new server response Builder object.
     */
    public static function init(bool $passed): self
    {
        return new self(new ServerResponse($passed));
    }

    /**
     * Sets message field.
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Sets input field.
     */
    public function input(?array $value): self
    {
        $this->instance->setInput($value);
        return $this;
    }

    /**
     * Initializes a new server response object.
     */
    public function build(): ServerResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
