<?php

declare(strict_types=1);

/*
 * TestForDatetimeInModelLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TestForDatetimeInModelLib\Models\Builders;

use Core\Utils\CoreHelper;
use TestForDatetimeInModelLib\Models\UnixDateTimeArray;

/**
 * Builder for model UnixDateTimeArray
 *
 * @see UnixDateTimeArray
 */
class UnixDateTimeArrayBuilder
{
    /**
     * @var UnixDateTimeArray
     */
    private $instance;

    private function __construct(UnixDateTimeArray $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new unix date time array Builder object.
     */
    public static function init(array $dateTime): self
    {
        return new self(new UnixDateTimeArray($dateTime));
    }

    /**
     * Initializes a new unix date time array object.
     */
    public function build(): UnixDateTimeArray
    {
        return CoreHelper::clone($this->instance);
    }
}
