<?php

declare(strict_types=1);

/*
 * TestForDatetimeInModelLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TestForDatetimeInModelLib\Models\Builders;

use Core\Utils\CoreHelper;
use TestForDatetimeInModelLib\Models\UnixDateTime;

/**
 * Builder for model UnixDateTime
 *
 * @see UnixDateTime
 */
class UnixDateTimeBuilder
{
    /**
     * @var UnixDateTime
     */
    private $instance;

    private function __construct(UnixDateTime $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new unix date time Builder object.
     */
    public static function init(\DateTime $dateTime): self
    {
        return new self(new UnixDateTime($dateTime));
    }

    /**
     * Initializes a new unix date time object.
     */
    public function build(): UnixDateTime
    {
        return CoreHelper::clone($this->instance);
    }
}
