<?php

declare(strict_types=1);

/*
 * TestForDatetimeInModelLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TestForDatetimeInModelLib\Models\Builders;

use Core\Utils\CoreHelper;
use TestForDatetimeInModelLib\Models\UnixDateTimeMap;

/**
 * Builder for model UnixDateTimeMap
 *
 * @see UnixDateTimeMap
 */
class UnixDateTimeMapBuilder
{
    /**
     * @var UnixDateTimeMap
     */
    private $instance;

    private function __construct(UnixDateTimeMap $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new unix date time map Builder object.
     */
    public static function init(array $dateTime): self
    {
        return new self(new UnixDateTimeMap($dateTime));
    }

    /**
     * Initializes a new unix date time map object.
     */
    public function build(): UnixDateTimeMap
    {
        return CoreHelper::clone($this->instance);
    }
}
