# test_for_datetime_in_model
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
module TestForDatetimeInModel
  # A utility  that supports dateTime conversion to different formats
  class DateTimeHelper < CoreLibrary::DateTimeHelper
  end
end
