# test_for_datetime_in_model
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'json'
require 'minitest/autorun'
require 'minitest/hell'
require 'minitest/pride'
require 'minitest/proveit'
require 'test_for_datetime_in_model'
require_relative '../http_response_catcher'

class ControllerTestBase < Minitest::Test
  parallelize_me!
  include TestForDatetimeInModel

  # Create configuration and set any test parameters
  def create_configuration
    Configuration.new(environment: Environment::TESTING,
                      http_callback: HttpResponseCatcher.new)
  end

  # Initializes the base test controller
  def setup_class
    _config = create_configuration
    @client = Client.new(config: _config)
  end
end
