# -*- coding: utf-8 -*-

"""
testfordatetimeinmodel

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from testfordatetimeinmodel.api_helper import APIHelper


class UnixDateTimeArray(object):

    """Implementation of the 'unix dateTime array' model.

    TODO: type model description here.

    Attributes:
        date_time (list of datetime): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "date_time": 'dateTime'
    }

    def __init__(self,
                 date_time=None):
        """Constructor for the UnixDateTimeArray class"""

        # Initialize members of the class
        if date_time is not None: 
            self.date_time = list()
            for x in date_time:
                self.date_time.append(APIHelper.UnixDateTime(x))

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        date_time = None
        if dictionary.get('dateTime') is not None:
            date_time = list()
            for x in dictionary.get('dateTime'):
                date_time.append(APIHelper.UnixDateTime.from_value(x).datetime)
        else:
            date_time = None
        # Return an object of this model
        return cls(date_time)
