# test_for_datetime_in_model
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module TestForDatetimeInModel
  # API utility class
  class APIHelper < CoreLibrary::ApiHelper
  end
end
