# test_for_datetime_in_model
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module TestForDatetimeInModel
  #  test_for_datetime_in_model client class.
  class Client
    attr_reader :config

    # Access to body_params controller.
    # @return [BodyParamsController] Returns the controller instance.
    def body_params
      @body_params ||= BodyParamsController.new @global_configuration
    end

    # Access to form_params controller.
    # @return [FormParamsController] Returns the controller instance.
    def form_params
      @form_params ||= FormParamsController.new @global_configuration
    end

    def initialize(connection: nil, adapter: :net_http_persistent, timeout: 60,
                   max_retries: 0, retry_interval: 1, backoff_factor: 2,
                   retry_statuses: [408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
                   retry_methods: %i[get put], http_callback: nil,
                   environment: Environment::TESTING, port: '80',
                   suites: SuiteCodeEnum::HEARTS, config: nil)
      @config = if config.nil?
                  Configuration.new(connection: connection, adapter: adapter,
                                    timeout: timeout, max_retries: max_retries,
                                    retry_interval: retry_interval,
                                    backoff_factor: backoff_factor,
                                    retry_statuses: retry_statuses,
                                    retry_methods: retry_methods,
                                    http_callback: http_callback,
                                    environment: environment, port: port,
                                    suites: suites)
                else
                  config
                end

      @global_configuration = GlobalConfiguration.new(client_configuration: @config)
                                                 .base_uri_executor(@config.method(:get_base_uri))
                                                 .global_errors(BaseController::GLOBAL_ERRORS)
                                                 .user_agent(BaseController.user_agent)
                                                 .sdk_module(TestForDatetimeInModel)
    end
  end
end
