/**
 * Test for Datetime in ModelLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface DateTimeModel {
  dateTime: string;
}

export const dateTimeModelSchema: Schema<DateTimeModel> = object({
  dateTime: ['dateTime', string()],
});
