/**
 * Test for Datetime in ModelLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

export interface Rfc3339DateTimeArray {
  dateTime: string[];
}

export const rfc3339DateTimeArraySchema: Schema<Rfc3339DateTimeArray> = object({
  dateTime: ['dateTime', array(string())],
});
