/**
 * Test for Datetime in ModelLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, object, Schema, string } from '../schema';

export interface Rfc3339DateTimeMap {
  dateTime: Record<string, string>;
}

export const rfc3339DateTimeMapSchema: Schema<Rfc3339DateTimeMap> = object({
  dateTime: ['dateTime', dict(string())],
});
