/**
 * Test for Datetime in ModelLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, Schema } from '../schema';

export interface UnixDateTimeArray {
  dateTime: number[];
}

export const unixDateTimeArraySchema: Schema<UnixDateTimeArray> = object({
  dateTime: ['dateTime', array(number())],
});
