/**
 * Test for Datetime in ModelLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, number, object, Schema } from '../schema';

export interface UnixDateTimeMap {
  dateTime: Record<string, number>;
}

export const unixDateTimeMapSchema: Schema<UnixDateTimeMap> = object({
  dateTime: ['dateTime', dict(number())],
});
