<?php

declare(strict_types=1);

/*
 * TestForDatetimeInModelLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TestForDatetimeInModelLib;

/**
 * Environments available for API
 */
class Environment
{
    public const PRODUCTION = 'production';

    public const TESTING = 'testing';
}
