# test_for_datetime_in_model
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module TestForDatetimeInModel
  # ServerResponse Model.
  class ServerResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [TrueClass|FalseClass]
    attr_accessor :passed

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :message

    # TODO: Write general description for this method
    # @return [Hash of Object]
    attr_accessor :input

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['passed'] = 'passed'
      @_hash['message'] = 'Message'
      @_hash['input'] = 'input'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        message
        input
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(passed = nil,
                   message = SKIP,
                   input = SKIP)
      @passed = passed
      @message = message unless message == SKIP
      @input = input unless input == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      passed = hash.key?('passed') ? hash['passed'] : nil
      message = hash.key?('Message') ? hash['Message'] : SKIP
      input = hash.key?('input') ? hash['input'] : SKIP

      # Create object from extracted values.
      ServerResponse.new(passed,
                         message,
                         input)
    end
  end
end
