# test_for_datetime_in_model
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
module TestForDatetimeInModel
  # UnixDateTime Model.
  class UnixDateTime < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :date_time

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['date_time'] = 'dateTime'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(date_time = nil)
      @date_time = date_time
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      date_time = if hash.key?('dateTime')
                    (DateTimeHelper.from_unix(hash['dateTime']) if hash['dateTime'])
                  end

      # Create object from extracted values.
      UnixDateTime.new(date_time)
    end

    def to_date_time
      DateTimeHelper.to_unix(date_time)
    end
  end
end
